<?php
/**
 * DISCONTINUED
 */
if($_SERVER['REQUEST_METHOD'] !="GET"&&$_SERVER['REQUEST_METHOD'] !="POST"&&$_SERVER['REQUEST_METHOD'] !="PUT"&&$_SERVER['REQUEST_METHOD'] !="DELETE") 
$execute="Invalid REQUEST_METHOD";
?>