<?php
/**
 * handles inter communications between the services
 * @package Connections
 * @author Tabernacle Of Testimony Church
 * @version 1.0.0
 * @access  protected
 * 
 */
class server2server
{
    /**
     * constructor
     */
    public function __construct()
    {
    }

    private function generate_query(string $link,array $data)
    {
        $link .="?";
        $started=false;
        foreach($data as $field_name =>$field_data)
        {
            if($started==false)
            {
                $link .=$field_name."=".$field_data;
                $started=true;
            }else $link .="&".$field_name."=".$field_data;
        }
        return $link;
    }
    /**
     * communicate,handles the communication between the service(Method)
     * @param array $data
     * @param string $link
     * @return bool|array $response
     * @access  protected
     * @copyright code automatically generated by postman API Testing tool
     */
    public function HTTP_REQ(string $request_method,array $data,string $link)
    {
        $link=$this->generate_query($link,$data);
        $curl = curl_init();
        curl_setopt_array($curl, array(
          CURLOPT_URL => $link,
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_FOLLOWLOCATION => true,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => $request_method
        ));
        $server_output = curl_exec($curl);
        curl_close($curl);
        if($server_output !=NULL)
        {
            return $server_output;
        }
        else if($server_output ==NULL)
        {
            return "false";
        }
    }

    

}
?>